version: "2"
services:
 # Jaeger
 jaeger:
   image: jaegertracing/all-in-one:latest
   networks:
     - backend
   ports:
     - "16686:16686"
     - "14268"
     - "14250"
     - "16685:16685"
 # Collector
 collector-gateway:
   image: otel/opentelemetry-collector:0.70.0
   volumes:
     - ./collector-gateway.yaml:/etc/collector-gateway.yaml
   networks:
     - backend
   command: [ "--config=/etc/collector-gateway.yaml" ]
   ports:
     - "13133:13133" # health_check extension
     - "4318:4317"        # OTLP gRPC receiver TODO
     - "4317:4318"        # OTLP HTTP receiver
     - "8889:8889" # zpages extension
   depends_on:
     - jaeger
     - data-prepper
     - rimrock
 data-prepper:
   restart: unless-stopped
   container_name: data-prepper
   image: opensearchproject/data-prepper:2
   volumes:
     - ./pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml
     - ./data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml
    #  - ./root-ca.pem:/usr/share/data-prepper/root-ca.pem
   ports:
     - "21890:21890"
     - "21891:21891"
   networks:
     - backend
   depends_on:
     - opensearch
 opensearch:
   image: opensearchproject/opensearch:2
   environment:
     - discovery.type=single-node
     - plugins.security.disabled=true
     - "OPENSEARCH_JAVA_OPTS=-Xms8192m -Xmx8192m"
   ulimits:
     memlock:
       soft: -1
       hard: -1
     nofile:
       soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
       hard: 65536
   volumes:
    - opensearch-data1:/usr/share/opensearch/data
   ports:
     - 9200:9200
     - 9600:9600 # required for Performance Analyzer
   networks:
     - backend
 dashboards:
   image: lwronski/opensearch-dashboards-no-security:0.1.0
   container_name: opensearch-dashboards
   ports:
     - 5601:5601
   environment:
    - plugins.security.disabled=true
    - OPENSEARCH_HOSTS=http://opensearch:9200
   volumes:
     - opensearch-data:/home/ubuntu/opensearch/data
   depends_on:
     - opensearch
   networks:
     - backend
 grafana:
   image: grafana/grafana:main
   environment: 
      # Disable authentication
     - GF_AUTH_DISABLE_LOGIN_FORM=true
     - GF_AUTH_ANONYMOUS_ENABLED=true
     - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
     - GF_USERS_ALLOW_SIGN_UP=false
     - GF_INSTALL_PLUGINS=grafana-opensearch-datasource
   volumes:
      - ./provisioning/:/etc/grafana/provisioning
      - 'grafana_storage:/var/lib/grafana'
   ports:
      - 3000:3000
   networks:
     - backend
 rimrock:
   image: lwronski/rimrock:0.13
   ports:
    - 8080:8080
   environment:
     - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://81.210.121.140:4318
     - OTEL_EXPORTER_OTLP_ENDPOINT=http://81.210.121.140:4318
     - OPENTELEMETRY_COLLECTOR_ENDPOINT=http://81.210.121.140:4318
     - OTEL_SERVICE_NAME=rimrock
   networks:
    - backend

 jupyterhub:
    image: quay.io/jupyterhub/jupyterhub
    container_name: jupyterhub
    ports:
      - "7601:7601"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/conf/observability:/srv/jupyterhub
    command: >
      bash -c "
      pip install oauthenticator dockerspawner jupyterhub-nativeauthenticator &&
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py
      "
    networks:
    - backend

volumes:
  opensearch-data:
  opensearch-data1:
  jupyterhub_data:
  grafana_storage: {}

networks:
  backend:
    driver: bridge
  jupyterhub:
    name: jupyterhub
     
