{
 "title": "AngioSupport monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "case_number",
    "query": "{\"find\": \"terms\", \"field\": \"metric.attributes.case_number.keyword\", \"size\": 1000}"
   }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Per Job RSS usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Pipeline: {{term metric.attributes.pipeline_name.keyword}}-{{term metric.attributes.pipeline_id.keyword}}, Step: {{metric.attributes.step_name.keyword}}, job_Id: {{metric.attributes.slurm_job_id.keyword}}, simulation: {{metric.attributes.simulation_id.keyword}}",
     "bucketAggs": [
      {
       "field": "metric.attributes.step_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.pipeline_id.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.pipeline_name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.slurm_job_id.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.simulation_id.keyword",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "max" }
     ],
     "query": "name:slurm_job_memory_total_rss AND metric.attributes.case_number:\"$case_number\"",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "Per Job cache memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Page Cache Memory of Pipeline: {{term metric.attributes.pipeline_name.keyword}}-{{term metric.attributes.pipeline_id.keyword}}, job_Id: {{metric.attributes.slurm_job_id.keyword}}, simulation: {{metric.attributes.simulation_id.keyword}}",
     "bucketAggs": [
      {
       "field": "metric.attributes.pipeline_id.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.pipeline_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.slurm_job_id.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.simulation_id.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "max" }
     ],
     "query": "name:slurm_job_memory_total_cache AND metric.attributes.case_number:\"$case_number\"",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "Per Job memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Pipeline: {{term metric.attributes.pipeline_name.keyword}}-{{term metric.attributes.pipeline_id.keyword}}, Step: {{metric.attributes.step_name.keyword}}, job_Id: {{metric.attributes.slurm_job_id.keyword}}, simulation: {{metric.attributes.simulation_id.keyword}}",
     "bucketAggs": [
      {
       "field": "metric.attributes.step_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.pipeline_id.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.pipeline_name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.slurm_job_id.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.simulation_id.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "max" }
     ],
     "query": "name:slurm_job_memory_usage AND metric.attributes.case_number:\"$case_number\"",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "Average memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Step: {{term metric.attributes.step_name.keyword}}",
     "bucketAggs": [
      {
       "field": "metric.attributes.pipeline_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.step_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "time", "id": "5", "settings": { "interval": "auto", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "name:slurm_job_memory_total_rss AND metric.attributes.case_number:\"$case_number\"",
     "timeField": "time"
    }
   ]
  },
  { "title": "CPU and files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Per job CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "alias": "Pipeline: {{term metric.attributes.pipeline_name.keyword}}-{{term metric.attributes.pipeline_id.keyword}}, Step: {{metric.attributes.step_name.keyword}}, job_Id: {{metric.attributes.slurm_job_id.keyword}}, simulation: {{metric.attributes.simulation_id.keyword}}",
     "bucketAggs": [
      {
       "field": "metric.attributes.step_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.pipeline_id.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.pipeline_name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.slurm_job_id.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.simulation_id.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "max" }
     ],
     "query": "name:slurm_job_cpu_percentage_usage AND metric.attributes.case_number:\"$case_number\"",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "Open files per step",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "alias": "Pipeline: {{term metric.attributes.pipeline_name.keyword}}-{{term metric.attributes.pipeline_id.keyword}}, Step: {{metric.attributes.step_name.keyword}}, job_Id: {{metric.attributes.slurm_job_id.keyword}}, simulation: {{metric.attributes.simulation_id.keyword}}",
     "bucketAggs": [
      {
       "field": "metric.attributes.pipeline_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.pipeline_id.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.step_name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.slurm_job_id.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.simulation_id.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "max" }
     ],
     "query": "name:slurm_job_open_files AND metric.attributes.case_number:\"$case_number\"",
     "timeField": "time"
    }
   ]
  }
 ]
}