{
 "title": "Per patient monitoring Prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "case_number", "query": { "query": "label_values(case_number)" } }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Per step RSS usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(step_name, pipeline_id, pipeline_name) (slurm_job_memory_total_rss{case_number=\"$case_number\"})",
     "legendFormat": "Pipeline: {{pipeline_name}}-{{pipeline_id}}, Step: {{step_name}}"
    }
   ]
  },
  {
   "title": "Per step RSS usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(step_name, pipeline_id, pipeline_name) (slurm_job_memory_total_rss{case_number=\"$case_number\"})",
     "legendFormat": "Pipeline: {{pipeline_name}}-{{pipeline_id}}, Step: {{step_name}}"
    }
   ]
  },
  {
   "title": "Average memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(step_name, pipeline_id) (slurm_job_memory_total_rss{case_number=\"$case_number\"})",
     "legendFormat": "Step: {{step_name}}"
    },
    {
     "expr": "sum by(case_number) (slurm_job_memory_total_rss{case_number=\"$case_number\"})",
     "legendFormat": "Patient: {{case_number}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Per step CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(step_name, pipeline_id, pipeline_name) (slurm_job_cpu_percent{case_number=\"$case_number\"})",
     "legendFormat": "Pipeline: {{pipeline_name}}-{{pipeline_id}}, Step: {{step_name}}"
    }
   ]
  },
  {
   "title": "Per pipeline CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(pipeline_id, pipeline_name) (slurm_job_cpu_percent{case_number=\"$case_number\"})",
     "legendFormat": "Pipeline: {{pipeline_name}}-{{pipeline_id}}"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Open files per step",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "slurm_job_open_files{case_number=\"$case_number\"}",
     "legendFormat": "Pipeline: {{pipeline_name}}-{{pipeline_id}}, Step: {{step_name}}"
    }
   ]
  },
  {
   "title": "Open files per pipeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by(pipeline_id, pipeline_name) (slurm_job_open_files{case_number=\"$case_number\"})",
     "legendFormat": "Pipeline: {{pipeline_name}}-{{pipeline_id}}"
    }
   ]
  }
 ]
}