{
 "title": "Per patient monitoring",
 "time": { "from": "2023-11-18T14:41:32.183Z", "to": "2023-11-18T14:51:05.796Z" },
 "templating": {
  "list": [
   { "name": "case_number", "query": { "query": "label_values(case_number)" } }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Per step RSS usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Pipeline: {{term metric.attributes.pipeline_name.keyword}}-{{term metric.attributes.pipeline_id}}, Step: {{metric.attributes.step_name.keyword}}",
     "bucketAggs": [
      {
       "field": "metric.attributes.step_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.pipeline_id",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.pipeline_name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "hide": false,
       "id": "1",
       "type": "min"
      }
     ],
     "query": "name:slurm_job_memory_total_rss AND metric.attributes.case_number:\"$case_number\"",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "Per pipeline memory allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "RSS of Pipeline: {{term metric.attributes.pipeline_name.keyword}}-{{term metric.attributes.pipeline_id}}",
     "bucketAggs": [
      {
       "field": "metric.attributes.pipeline_id",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.pipeline_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "time", "id": "1", "settings": { "interval": "5s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "max" }
     ],
     "query": "name:slurm_job_memory_total_rss AND metric.attributes.case_number:\"$case_number\"",
     "timeField": "time"
    },
    {
     "alias": "Page Cache Memory of Pipeline: {{term metric.attributes.pipeline_name.keyword}}-{{term metric.attributes.pipeline_id}}",
     "bucketAggs": [
      {
       "field": "metric.attributes.pipeline_id",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.pipeline_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "min" }
     ],
     "query": "name:slurm_job_memory_total_cache AND metric.attributes.case_number:\"$case_number\"",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "Average memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Step: {{term metric.attributes.step_name.keyword}}",
     "bucketAggs": [
      {
       "field": "metric.attributes.pipeline_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.step_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "time", "id": "5", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "avg" }
     ],
     "query": "name:slurm_job_memory_total_rss AND metric.attributes.case_number:\"$case_number\"",
     "timeField": "time"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Per step CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": "Pipeline: {{term metric.attributes.pipeline_name.keyword}}-{{term metric.attributes.pipeline_id}}, Step: {{metric.attributes.step_name.keyword}}",
     "bucketAggs": [
      {
       "field": "metric.attributes.step_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.pipeline_id",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.pipeline_name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "min" }
     ],
     "query": "name:slurm_job_cpu_percent AND metric.attributes.case_number:\"$case_number\"",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "Per pipeline CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "alias": "Pipeline: {{term metric.attributes.pipeline_name.keyword}}-{{term metric.attributes.pipeline_id}}",
     "bucketAggs": [
      {
       "field": "metric.attributes.pipeline_id",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.pipeline_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "time", "id": "2", "settings": { "interval": "5s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "min" }
     ],
     "query": "name:slurm_job_cpu_percent AND metric.attributes.case_number:\"$case_number\"",
     "timeField": "time"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Open files per step",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "alias": "Pipeline: {{term metric.attributes.pipeline_name.keyword}}-{{term metric.attributes.pipeline_id}}, Step: {{metric.attributes.step_name.keyword}}",
     "bucketAggs": [
      {
       "field": "metric.attributes.pipeline_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.pipeline_id",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.step_name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "min" }
     ],
     "query": "name:slurm_job_open_files AND metric.attributes.case_number:\"$case_number\"",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "Open files per pipeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "alias": "Pipeline: {{term metric.attributes.pipeline_name.keyword}}-{{term metric.attributes.pipeline_id}}",
     "bucketAggs": [
      {
       "field": "metric.attributes.pipeline_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "metric.attributes.pipeline_id",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "min" }
     ],
     "query": "name:slurm_job_open_files AND metric.attributes.case_number:\"$case_number\"",
     "timeField": "time"
    }
   ]
  }
 ]
}