{
 "title": "Per user monitoring",
 "time": { "from": "2023-11-18T14:42:53.170Z", "to": "2023-11-18T14:49:39.434Z" },
 "templating": {
  "list": [
   { "name": "plgUser", "query": { "query": "label_values(user)" } }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "RSS usage",
     "bucketAggs": [
      {
       "field": "metric.attributes.user.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "sum" }
     ],
     "query": "name:slurm_job_memory_total_rss AND metric.attributes.user.keyword:\"$plgUser\"",
     "timeField": "time"
    },
    {
     "alias": "Cache memory",
     "bucketAggs": [
      {
       "field": "metric.attributes.user.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "sum" }
     ],
     "query": "name:slurm_job_memory_total_cache AND metric.attributes.user.keyword:\"$plgUser\"",
     "timeField": "time"
    }
   ]
  },
  { "title": "Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Open files per user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 10 },
   "targets": [
    {
     "alias": "Open files",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "value", "id": "1", "type": "sum" }
     ],
     "query": "name:slurm_job_open_files AND metric.attributes.user.keyword:\"$plgUser\"",
     "timeField": "time"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Avg % of CPU usage per user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 19 },
   "targets": [
    {
     "alias": "CPU usage",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "name:slurm_job_cpu_percent AND metric.attributes.user.keyword:\"$plgUser\"",
     "timeField": "time"
    }
   ]
  }
 ]
}