{
 "title": "Per user monitoring Prometheus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "plgUser", "query": { "query": "label_values(user)" } }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(user) (slurm_job_memory_total_rss{user=\"$plgUser\"})",
     "legendFormat": "rss memory"
    },
    {
     "expr": "sum(slurm_job_memory_total_cache{user=\"$plgUser\"})",
     "legendFormat": "cache memory"
    }
   ]
  },
  {
   "title": "Min memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum by(user) (slurm_job_memory_total_rss{user=\"$plgUser\"})",
     "legendFormat": "for user: {{user}}"
    }
   ]
  },
  {
   "title": "Avg memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(user) (slurm_job_memory_total_rss{user=\"$plgUser\"})",
     "legendFormat": "for user: {{user}}"
    }
   ]
  },
  {
   "title": "Max memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(user) (slurm_job_memory_total_rss{user=\"$plgUser\"})",
     "legendFormat": "for user: {{user}}"
    }
   ]
  },
  { "title": "Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Open files per user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 10 },
   "targets": [
    {
     "expr": "sum by(user) (slurm_job_open_files{user=\"$plgUser\"})",
     "legendFormat": "open files"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "avg % of CPU usage by user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 19 },
   "targets": [
    {
     "expr": "sum by(user) (slurm_job_cpu_percent{user=\"$plgUser\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}